api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['appliction/json']
        jsonld: ['appliction/ld+json']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: false
